# PostgreSQL local (pour test)
spring.datasource.url=jdbc:postgresql://localhost:5432/Semaine_tco_db
spring.datasource.username=postgres
spring.datasource.password=tendry

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080
server.address=0.0.0.0

# Email (pour test)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tendryandriarisoa2@gmail.com
spring.mail.password=jkkl tyek cyht iysb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application URL (local)
app.base.url=http://localhost:8080