spring.datasource.url=jdbc:postgresql://localhost:5432/Semaine_tco_db
spring.datasource.username=postgres
spring.datasource.password=tendry

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# =====================================================
# EMAIL CONFIGURATION
# =====================================================

# Configuration SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tendryandriarisoa2@gmail.com
spring.mail.password=jkkl tyek cyht iysb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration alternative (Outlook)
# spring.mail.host=smtp.office365.com
# spring.mail.port=587

# Template emails
spring.mail.templates.path=classpath:/templates/email/

# Application URL
app.base.url=http://192.168.137.45:8080
# WebJars
spring.mvc.webjars.enabled=true
server.port=8080
server.address=0.0.0.0